os:
    - linux
    - osx

osx_image: xcode9.3

language: java

jdk:
    - openjdk8
    - openjdk11
    - openjdk12

env:
    - GRAALVM_VERSION="20.3.0"

matrix:
    exclude:
        - jdk: openjdk8
          os: osx

install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
        curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
        tar -xzf graalvm.tar.gz

script:
    - mvn clean
    - mvn package
    - mvn exec:exec
    - if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" ]]; then mvn exec:exec@nograal; fi
    - export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
    - mvn clean
    - mvn package
    - mvn exec:exec
